agencia-viajes-back/config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :destinations
  resources :customers
  resources :tokens

end

agencia-viajes-back/app/models/token.rb
# == Schema Information
#
# Table name: tokens
#
#  id                :integer          not null, primary key
#  token             :string
#  number_of_request :integer          default(0)
#  status            :boolean          default(TRUE)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Token < ActiveRecord::Base
	before_create :asignar_token

	validates :number_of_request, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

	def self.authenticate(auth_token)
		find_by(token: auth_token)
	end

	private
	
	def asignar_token
		self.token = SecureRandom.uuid
	end
	
end

agencia-viajes-back/app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: [:show, :edit, :update, :destroy]

  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
  end

  # GET /tokens/new
  def new
    @token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  # POST /tokens
  # POST /tokens.json
  def create
    @token = Token.new(token_params)

    respond_to do |format|
      if @token.save
        format.html { redirect_to @token, notice: 'Token was successfully created.' }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1
  # PATCH/PUT /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to @token, notice: 'Token was successfully updated.' }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token.destroy
    respond_to do |format|
      format.html { redirect_to tokens_url, notice: 'Token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = Token.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_params
      params.require(:token).permit(:token, :number_of_request, :status)
    end
end

agencia-viajes-back/app/helpers/tokens_helper.rb
module TokensHelper
end

agencia-viajes-back/app/views/tokens/_form.html.erb
<%= form_for(@token) do |f| %>
  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :number_of_request %><br>
    <%= f.number_field :number_of_request %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

agencia-viajes-back/app/views/tokens/edit.html.erb
<h1>Editing Token</h1>

<%= render 'form' %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

agencia-viajes-back/app/views/tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Number of request</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.token %></td>
        <td><%= token.number_of_request %></td>
        <td><%= token.status %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path %>

agencia-viajes-back/app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form' %>

<%= link_to 'Back', tokens_path %>

agencia-viajes-back/app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @token.token %>
</p>

<p>
  <strong>Number of request:</strong>
  <%= @token.number_of_request %>
</p>

<p>
  <strong>Status:</strong>
  <%= @token.status %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>