agencia-viajes-front/config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :permissions
  resources :session_logs
  resources :users

  resources :customers
  resources :destinations
  resources :sales
  resources :tokens

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'

  get '/tokens', to: 'tokens#index'
  get '/destinations', to: 'destinations#index'
  get '/sales', to: 'sales#index'
  

end

agencia-viajes-front/app/models/destination.rb
require_relative 'http_base'

class Destination < HttpBase
	include ActiveModel::Model

	attr_accessor :city, :country, :price, :taxes, :total, :status, :id, :created_at, :updated_at, :url

	validates :city, presence: true, length: 3..30
	validates :country, presence: true, length: 3..30
	validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :taxes, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :total, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

	def initialize(params = {})
		params.each do |key, val|
			self.send("#{key}=", val)
		end
	end

	def persisted?
		self.id.present?
	end

	def self.endpoint
		'/destinations'
	end

	def self.all
		response = HTTParty.get(path, headers: { 'token' => TOKEN })
		response.parsed_response.map do |destination|
			new(destination)
		end
	end

	def self.find(destination_id)
		response = HTTParty.get(path("/#{destination_id}"), headers: { 'token' => TOKEN })
		new(response.parsed_response)
	end

	def update
		HTTParty.put(self.class.path("/#{id}"), query: to_json, headers: { 'token' => TOKEN })
	end

	def save
		HTTParty.post(self.class.path, query: to_json, headers: { 'token' => TOKEN })
	end

	def destroy
		HTTParty.delete(self.class.path("/#{id}"), headers: { 'token' => TOKEN })
	end

	def to_json
		{
			destination: {
				city: self.city,
				country: self.country,
				price: self.price,
				taxes: self.taxes,
				total: self.total,
				status: self.status
			}
		}
	end

end

agencia-viajes-front/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :logged_in?
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    @destination = Destination.new(destination_params)
    @destination.id = params[:id]

    respond_to do |format|
      if @destination.update
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :price, :taxes, :total, :status)
    end
end

agencia-viajes-front/app/helpers/destinations_helper.rb
module DestinationsHelper
end

agencia-viajes-front/app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :taxes %><br>
    <%= f.number_field :taxes %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

agencia-viajes-front/app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

agencia-viajes-front/app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Destinations</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Country</th>
      <th>Price</th>
      <th>Taxes</th>
      <th>Total</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= destination.city %></td>
        <td><%= destination.country %></td>
        <td><%= destination.price %></td>
        <td><%= destination.taxes %></td>
        <td><%= destination.total %></td>
        <td><%= destination.status ? 'Active' : 'Inactive' %></td>
        <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination', new_destination_path %>

agencia-viajes-front/app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

agencia-viajes-front/app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @destination.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @destination.country %>
</p>

<p>
  <strong>Price:</strong>
  <%= @destination.price %>
</p>

<p>
  <strong>Taxes:</strong>
  <%= @destination.taxes %>
</p>

<p>
  <strong>Total:</strong>
  <%= @destination.total %>
</p>

<p>
  <strong>Status:</strong>
  <%= @destination.status ? 'Active' : 'Inactive' %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>